[platformio] ; PlatformIO config options
src_dir = C:\Users\willig6\Desktop\puckmelt\spring_2026\BLE_Client_connect ; treat this folder as source (keep Arduino structure)

[env] ; Shared environment options
platform = espressif32
framework = arduino
monitor_speed = 115200 ;baud rate for serial monitor
monitor_filters = esp32_exception_decoder
build_type = debug

[env:s3] ; specific environment options
board = lolin_s3_mini
upload_port = COM6
board_build.partitions = min_spiffs.csv
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1

[env:otas3] ; specific environment options
board = lolin_s3_mini
upload_protocol = espota
board_build.partitions = min_spiffs.csv
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1